name: better_player_web
version: 1.0.0

publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: BetterPlayerWeb
        fileName: better_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

#  video_js:
#    path: '../../video_js'

  better_player_platform_interface:
    git:
      url: https://github.com/uniqcast/betterplayer
      ref: 295a9817f74e30f57d53dbd3f64a8499e94433bf
      path: better_player_platform_interface
  js: ^0.6.4
#  better_player_platform_interface:
#    path: '../better_player_platform_interface'

dev_dependencies:
  flutter_lints: ^2.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"