name: better_player_ios
description: iOS implementation of the better_player plugin.
repository: https://github.com/uniqcast/betterplayer
issue_tracker: https://github.com/uniqcast/betterplayer/issues
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: better_player
    platforms:
      ios:
        dartPluginClass: IosBetterPlayer
        pluginClass: BetterPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  better_player_platform_interface:
    git:
      url: https://github.com/uniqcast/betterplayer
      ref: afc24df1c8452aa71c01828c99da8dd355167872
      path: better_player_platform_interface
#  better_player_platform_interface:
#    path: ../better_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^2.0.1
