name: better_player_platform_interface
description: A common platform interface for the better_player plugin.
repository: https://github.com/jhomlala/betterplayer
issue_tracker: https://github.com/jhomlala/betterplayer/issues
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: 3.2.0
